### ISSUE TITLE
[1.3.2] Crash on re-entering old world

### ISSUE THREAD

**Issue by Sereath** [ACGaming/ExtraSoundsLegacy#10]
https://mclo.gs/jJaDcOp

```
Description: Ticking memory connection

java.lang.NullPointerException
    at net.minecraft.client.multiplayer.WorldClient.playSound(WorldClient.java:579)
    at net.minecraft.client.multiplayer.WorldClient.playSound(WorldClient.java:568)
    at net.minecraft.world.World.playSound(World.java:1116)
    at mod.acgaming.extrasounds.sound.ESSoundManager.playSoundWorld(ESSoundManager.java:221)
    at net.minecraft.entity.player.EntityPlayer.onNewPotionEffect(EntityPlayer.java:3533)
    at net.minecraft.entity.player.EntityPlayerMP.onNewPotionEffect(EntityPlayerMP.java:1186)
    at net.minecraft.entity.EntityLivingBase.addPotionEffect(EntityLivingBase.java:751)
    at dev.lonami.logimmune.Buffs.buff(Buffs.java:15)
    at dev.lonami.logimmune.LogImmune.buffPlayer(LogImmune.java:74)
    at dev.lonami.logimmune.LogImmune.onLogin(LogImmune.java:59)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2667_LogImmune_onLogin_PlayerLoggedInEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
    at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
    at shadows.fastbench.net.HijackedPlayerList.initializeConnectionToPlayer(HijackedPlayerList.java:19)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:205)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```
```
  Suspected Mods: Extra Sounds (extrasounds), Log Immune (logimmune), Forge Mod Loader (FML), Minecraft Forge (forge), FastWorkbench (fastbench)
```

**Comment by ACGaming** [comment]
Looks like the mod „Log Immune“ grants a resistance buff before the client world is fully loaded, gotta handle this.

**Comment by ACGaming** [comment]
Unable to reproduce though, does it happen on every re-join?

**Comment by ACGaming** [comment]
The workaround was hilariously easy. Since I had to limit the potion effects to the player only, I can just let the sounds play at the player like supposed to.
